# Generated by Django 6.0.1 on 2026-07-02 15:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_alumnos_updated_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
